import { Element } from './element.model';
export var tableOfElements: Element[] = [{"atomicNumber":1,"symbol":"H","name":"Hydrogen","atomicMass":1.07947, "group": 1, "period": 1, "block": "s"},
    {"atomicNumber":2,"symbol":"He","name":"Helium","atomicMass":4.002602, "group": 18, "period": 1, "block": "s"},
    {"atomicNumber":3,"symbol":"Li","name":"Lithium","atomicMass":6.941, "group": 1, "period": 2, "block": "s"},
    {"atomicNumber":4,"symbol":"Be","name":"Beryllium","atomicMass":9.012182, "group": 2, "period": 2, "block": "s"},
    {"atomicNumber":5,"symbol":"B","name":"Boron","atomicMass":10.811, "group": 13, "period": 2, "block": "p"},
    {"atomicNumber":6,"symbol":"C","name":"Carbon","atomicMass":12.0107, "group": 14, "period": 2, "block": "p"},
    {"atomicNumber":7,"symbol":"N","name":"Nitrogen","atomicMass":14.0067, "group": 15, "period": 2, "block": "p"},
    {"atomicNumber":8,"symbol":"O","name":"Oxygen","atomicMass":15.9994, "group": 16, "period": 2, "block": "p"},
    {"atomicNumber":9,"symbol":"F","name":"Fluorine","atomicMass":18.9994, "group": 17, "period": 2, "block": "p"},
    {"atomicNumber":10,"symbol":"Ne","name":"Neon","atomicMass":20.1797, "group": 18, "period": 2, "block": "p"},
    {"atomicNumber":11,"symbol":"Na","name":"Sodium","atomicMass":22.98976928, "group": 1, "period": 3, "block": "s"},
    { "atomicNumber": 12, "symbol": "Mg", "name": "Magnesium", "atomicMass": 24.305, "group": 2, "period": 3, "block": "s" },
    { "atomicNumber": 13, "symbol": "Al", "name": "Aluminium", "atomicMass": 26.9815386, "group": 13, "period": 3, "block": "p" },
    { "atomicNumber": 14, "symbol": "Si", "name": "Silicon", "atomicMass": 28.0855, "group": 14, "period": 3, "block": "p" },
    { "atomicNumber": 15, "symbol": "P", "name": "Phosphorus", "atomicMass": 30.973762, "group": 15, "period": 3, "block": "p" },
    { "atomicNumber": 16, "symbol": "S", "name": "Sulphur", "atomicMass": 32.065, "group": 16, "period": 3, "block": "p" },
    { "atomicNumber": 17, "symbol": "Cl", "name": "Chlorine", "atomicMass": 35.453, "group": 17, "period": 3, "block": "p" },
    { "atomicNumber": 18, "symbol": "Ar", "name": "Argon", "atomicMass": 39.948, "group": 18, "period": 3, "block": "p" },
    { "atomicNumber": 19, "symbol": "K", "name": "Potassium", "atomicMass": 39.0983, "group": 1, "period": 4, "block": "s" },
    { "atomicNumber": 20, "symbol": "Ca", "name": "Calcium", "atomicMass": 40.078, "group": 2, "period": 4, "block": "s" },
    { "atomicNumber": 21, "symbol": "Sc", "name": "Scandium", "atomicMass": 44.955912, "group": 3, "period": 4, "block": "d" },
    { "atomicNumber": 22, "symbol": "Ti", "name": "Titanium", "atomicMass": 47.867, "group": 4, "period": 4, "block": "d" },
    { "atomicNumber": 23, "symbol": "V", "name": "Vanadium", "atomicMass": 50.9415, "group": 5, "period": 4, "block": "d" },
    { "atomicNumber": 24, "symbol": "Cr", "name": "Chromium", "atomicMass": 51.9961, "group": 6, "period": 4, "block": "d" },
    { "atomicNumber": 25, "symbol": "Mn", "name": "Manganese", "atomicMass": 54.938045, "group": 7, "period": 4, "block": "d" },
    { "atomicNumber": 26, "symbol": "Fe", "name": "Iron", "atomicMass": 55.845, "group": 8, "period": 4, "block": "d" },
    { "atomicNumber": 27, "symbol": "Co", "name": "Cobalt", "atomicMass": 58.933195, "group": 9, "period": 4, "block": "d" },
    { "atomicNumber": 28, "symbol": "Ni", "name": "Nickel", "atomicMass": 58.6934, "group": 10, "period": 4, "block": "d" },
    { "atomicNumber": 29, "symbol": "Cu", "name": "Copper", "atomicMass": 63.546, "group": 11, "period": 4, "block": "d" },
    { "atomicNumber": 30, "symbol": "Zn", "name": "Zinc", "atomicMass": 65.38, "group": 12, "period": 4, "block": "d" },
    { "atomicNumber": 31, "symbol": "Ga", "name": "Gallium", "atomicMass": 69.723, "group": 13, "period": 4, "block": "p" },
    { "atomicNumber": 32, "symbol": "Ge", "name": "Germanium", "atomicMass": 72.64, "group": 14, "period": 4, "block": "p" },
    { "atomicNumber": 33, "symbol": "As", "name": "Arsenic", "atomicMass": 74.9216, "group": 15, "period": 4, "block": "p" },
    { "atomicNumber": 34, "symbol": "Se", "name": "Selenium", "atomicMass": 78.96, "group": 16, "period": 4, "block": "p" },
    { "atomicNumber": 35, "symbol": "Br", "name": "Bromine", "atomicMass": 79.904, "group": 17, "period": 4, "block": "p" },
    { "atomicNumber": 36, "symbol": "Kr", "name": "Krypton", "atomicMass": 83.798, "group": 18, "period": 4, "block": "p" },
    { "atomicNumber": 37, "symbol": "Rb", "name": "Rubidium", "atomicMass": 85.4678, "group": 1, "period": 5, "block": "s" },
    { "atomicNumber": 38, "symbol": "Sr", "name": "Strontium", "atomicMass": 87.62, "group": 2, "period": 5, "block": "s" },
    { "atomicNumber": 39, "symbol": "Y", "name": "Yttrium", "atomicMass": 88.90585, "group": 3, "period": 5, "block": "d" },
    { "atomicNumber": 40, "symbol": "Zr", "name": "Zirkonium", "atomicMass": 91.224, "group": 4, "period": 5, "block": "d" },
    { "atomicNumber": 41, "symbol": "Nb", "name": "Niobium", "atomicMass": 92.90638, "group": 5, "period": 5, "block": "d" },
    { "atomicNumber": 42, "symbol": "Mo", "name": "Molybdaenum", "atomicMass": 95.96, "group": 6, "period": 5, "block": "d" },
    { "atomicNumber": 43, "symbol": "Tc", "name": "Technetium", "atomicMass": 98, "group": 7, "period": 5, "block": "d" },
    { "atomicNumber": 44, "symbol": "Ru", "name": "Ruthenium", "atomicMass": 101.07, "group": 8, "period": 5, "block": "d" },
    { "atomicNumber": 45, "symbol": "Rh", "name": "Rhodium", "atomicMass": 102.9055, "group": 9, "period": 5, "block": "d" },
    { "atomicNumber": 46, "symbol": "Pd", "name": "Palladium", "atomicMass": 106.42, "group": 10, "period": 5, "block": "d" },
    { "atomicNumber": 47, "symbol": "Ag", "name": "Silver", "atomicMass": 107.8682, "group": 11, "period": 5, "block": "d" },
    { "atomicNumber": 48, "symbol": "Cd", "name": "Cadmium", "atomicMass": 112.411, "group": 12, "period": 5, "block": "d" },
    { "atomicNumber": 49, "symbol": "In", "name": "Indium", "atomicMass": 114.818, "group": 13, "period": 5, "block": "p" },
    { "atomicNumber": 50, "symbol": "Sn", "name": "Tin", "atomicMass": 118.71, "group": 14, "period": 5, "block": "p" },
    { "atomicNumber": 51, "symbol": "Sb", "name": "Antimony", "atomicMass": 121.76, "group": 15, "period": 5, "block": "p" },
    { "atomicNumber": 52, "symbol": "Te", "name": "Tellurium", "atomicMass": 127.6, "group": 16, "period": 5, "block": "p" },
    { "atomicNumber": 53, "symbol": "I", "name": "Iodine", "atomicMass": 126.90447, "group": 17, "period": 5, "block": "p" },
    { "atomicNumber": 54, "symbol": "Xe", "name": "Xenon", "atomicMass": 131.293, "group": 18, "period": 5, "block": "p" },
    { "atomicNumber": 55, "symbol": "Cs", "name": "Cesium", "atomicMass": 132.9054519, "group": 1, "period": 6, "block": "s" },
    { "atomicNumber": 56, "symbol": "Ba", "name": "Barium", "atomicMass": 137.327, "group": 2, "period": 6, "block": "s" },
    { "atomicNumber": 57, "symbol": "La", "name": "Lanthanum", "atomicMass": 138.90547, "group": 19, "period": 6, "block": "f" },
    { "atomicNumber": 58, "symbol": "Ce", "name": "Cerium", "atomicMass": 140.116, "group": 20, "period": 6, "block": "f" },
    { "atomicNumber": 59, "symbol": "Pr", "name": "Praseodymium", "atomicMass": 140.90765, "group": 21, "period": 6, "block": "f" },
    { "atomicNumber": 60, "symbol": "Nd", "name": "Neodymium", "atomicMass": 144.242, "group": 22, "period": 6, "block": "f" },
    { "atomicNumber": 61, "symbol": "Pm", "name": "Promethium", "atomicMass": 145, "group": 23, "period": 6, "block": "f" },
    { "atomicNumber": 62, "symbol": "Sm", "name": "Samarium", "atomicMass": 150.36, "group": 24, "period": 6, "block": "f" },
    { "atomicNumber": 63, "symbol": "Eu", "name": "Europium", "atomicMass": 151.964, "group": 25, "period": 6, "block": "f" },
    { "atomicNumber": 64, "symbol": "Gd", "name": "Gadolinium", "atomicMass": 157.25, "group": 26, "period": 6, "block": "f" },
    { "atomicNumber": 65, "symbol": "Tb", "name": "Terbium", "atomicMass": 158.92535, "group": 27, "period": 6, "block": "f" },
    { "atomicNumber": 66, "symbol": "Dy", "name": "Dysprosium", "atomicMass": 162.5001, "group": 28, "period": 6, "block": "f" },
    { "atomicNumber": 67, "symbol": "Ho", "name": "Holmium", "atomicMass": 164.93032, "group": 29, "period": 6, "block": "f" },
    { "atomicNumber": 68, "symbol": "Er", "name": "Erbium", "atomicMass": 167.259, "group": 30, "period": 6, "block": "f" },
    { "atomicNumber": 69, "symbol": "Tm", "name": "Thulium", "atomicMass": 168.93421, "group": 31, "period": 6, "block": "f" },
    { "atomicNumber": 70, "symbol": "Yb", "name": "Ytterbium", "atomicMass": 173.054, "group": 32, "period": 6, "block": "f" },
    { "atomicNumber": 71, "symbol": "Lu", "name": "Lutetium", "atomicMass": 174.9668, "group": 33, "period": 6, "block": "f" },
    { "atomicNumber": 72, "symbol": "Hf", "name": "Hafnium", "atomicMass": 178.49, "group": 4, "period": 6, "block": "d" },
    { "atomicNumber": 73, "symbol": "Ta", "name": "Tantalum", "atomicMass": 180.94788, "group": 5, "period": 6, "block": "d" },
    { "atomicNumber": 74, "symbol": "W", "name": "Tungsten", "atomicMass": 183.84, "group": 6, "period": 6, "block": "d" },
    { "atomicNumber": 75, "symbol": "Re", "name": "Rhenium", "atomicMass": 186.207, "group": 7, "period": 6, "block": "d" },
    { "atomicNumber": 76, "symbol": "Os", "name": "Osmium", "atomicMass": 190.23, "group": 8, "period": 6, "block": "d" },
    { "atomicNumber": 77, "symbol": "Ir", "name": "Iridium", "atomicMass": 192.217, "group": 9, "period": 6, "block": "d" },
    { "atomicNumber": 78, "symbol": "Pt", "name": "Platinum", "atomicMass": 192.084, "group": 10, "period": 6, "block": "d" },
    { "atomicNumber": 79, "symbol": "Au", "name": "Gold", "atomicMass": 196.966569, "group": 11, "period": 6, "block": "d" },
    { "atomicNumber": 80, "symbol": "Hg", "name": "Hydrargyrum", "atomicMass": 200.59, "group": 12, "period": 6, "block": "d" },
    { "atomicNumber": 81, "symbol": "Tl", "name": "Thallium", "atomicMass": 204.3833, "group": 13, "period": 6, "block": "p" },
    { "atomicNumber": 82, "symbol": "Pb", "name": "Lead", "atomicMass": 207.2, "group": 14, "period": 6, "block": "p" },
    { "atomicNumber": 83, "symbol": "Bi", "name": "Bismuth", "atomicMass": 208.980401, "group": 15, "period": 6, "block": "p" },
    { "atomicNumber": 84, "symbol": "Po", "name": "Polonium", "atomicMass": 210, "group": 16, "period": 6, "block": "p" },
    { "atomicNumber": 85, "symbol": "At", "name": "Astatine", "atomicMass": 210, "group": 17, "period": 6, "block": "p" },
    { "atomicNumber": 86, "symbol": "Rn", "name": "Radon", "atomicMass": 220, "group": 18, "period": 6, "block": "p" },
    { "atomicNumber": 87, "symbol": "Fr", "name": "Francium", "atomicMass": 223, "group": 1, "period": 7, "block": "s" },
    { "atomicNumber": 88, "symbol": "Ra", "name": "Radium", "atomicMass": 226, "group": 2, "period": 7, "block": "s" },
    { "atomicNumber": 89, "symbol": "Ac", "name": "Actinium", "atomicMass": 227, "group": 19, "period": 7, "block": "f" },
    { "atomicNumber": 90, "symbol": "Th", "name": "Thorium", "atomicMass": 232.03806, "group": 20, "period": 7, "block": "f" },
    { "atomicNumber": 91, "symbol": "Pa", "name": "Protactinium", "atomicMass": 231.03588, "group": 21, "period": 7, "block": "f" },
    { "atomicNumber": 92, "symbol": "U", "name": "Uranium", "atomicMass": 238.02891, "group": 22, "period": 7, "block": "f" },
    { "atomicNumber": 93, "symbol": "Np", "name": "Neptunium", "atomicMass": 237, "group": 23, "period": 7, "block": "f" },
    { "atomicNumber": 94, "symbol": "Pu", "name": "Plutonium", "atomicMass": 244, "group": 24, "period": 7, "block": "f" },
    { "atomicNumber": 95, "symbol": "Am", "name": "Americium", "atomicMass": 243, "group": 25, "period": 7, "block": "f" },
    { "atomicNumber": 96, "symbol": "Cm", "name": "Curium", "atomicMass": 247, "group": 26, "period": 7, "block": "f" },
    { "atomicNumber": 97, "symbol": "Bk", "name": "Berkelium", "atomicMass": 247, "group": 27, "period": 7, "block": "f" },
    { "atomicNumber": 98, "symbol": "Cf", "name": "Californium", "atomicMass": 251, "group": 28, "period": 7, "block": "f" },
    { "atomicNumber": 99, "symbol": "Es", "name": "Einsteinium", "atomicMass": 252, "group": 29, "period": 7, "block": "f" },
    { "atomicNumber": 100, "symbol": "Fm", "name": "Fermium", "atomicMass": 257, "group": 30, "period": 7, "block": "f" },
    { "atomicNumber": 101, "symbol": "Md", "name": "Mendelevium", "atomicMass": 258, "group": 31, "period": 7, "block": "f" },
    { "atomicNumber": 102, "symbol": "No", "name": "Nobelium", "atomicMass": 259, "group": 32, "period": 7, "block": "f" },
    { "atomicNumber": 103, "symbol": "Lr", "name": "Lawrencium", "atomicMass": 262, "group": 33, "period": 7, "block": "f" },
    { "atomicNumber": 104, "symbol": "Rf", "name": "Rutherfordium", "atomicMass": 261, "group": 4, "period": 7, "block": "d" },
    { "atomicNumber": 105, "symbol": "Db", "name": "Dubnium", "atomicMass": 262, "group": 5, "period": 7, "block": "d" },
    { "atomicNumber": 106, "symbol": "Sg", "name": "Seaborgium", "atomicMass": 266, "group": 6, "period": 7, "block": "d" },
    { "atomicNumber": 107, "symbol": "Bh", "name": "Bohrium", "atomicMass": 264, "group": 7, "period": 7, "block": "d" },
    { "atomicNumber": 108, "symbol": "Hs", "name": "Hassium", "atomicMass": 277, "group": 8, "period": 7, "block": "d" },
    { "atomicNumber": 109, "symbol": "Mt", "name": "Meitnerium", "atomicMass": 268, "group": 9, "period": 7, "block": "d" },
    { "atomicNumber": 110, "symbol": "Ds", "name": "Ununnilium", "atomicMass": 271, "group": 10, "period": 7, "block": "d" },
    { "atomicNumber": 111, "symbol": "Rg", "name": "Unununium", "atomicMass": 272, "group": 11, "period": 7, "block": "d" },
    { "atomicNumber": 112, "symbol": "Uub", "name": "Ununbium", "atomicMass": 285, "group": 12, "period": 7, "block": "d" },
    { "atomicNumber": 113, "symbol": "Uut", "name": "Ununtrium", "atomicMass": 284, "group": 13, "period": 7, "block": "p" },
    { "atomicNumber": 114, "symbol": "Uuq", "name": "Ununquadium", "atomicMass": 289, "group": 14, "period": 7, "block": "p" },
    { "atomicNumber": 115, "symbol": "Uup", "name": "Ununpentium", "atomicMass": 288, "group": 15, "period": 7, "block": "p" },
    { "atomicNumber": 116, "symbol": "Uuh", "name": "Ununhexium", "atomicMass": 292, "group": 16, "period": 7, "block": "p" },
    { "atomicNumber": 117, "symbol": "Uus", "name": "Ununseptium", "atomicMass": 294, "group": 17, "period": 7, "block": "p" },
    { "atomicNumber": 118, "symbol": "Uuo", "name": "Ununoctium", "atomicMass": 294, "group": 18, "period": 7, "block": "p" }]